name: INSTALL-TEST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run install script
        run: |
          ./installROS2.sh
          source /opt/ros/foxy/setup.bash
          ros2
